<a href="https://colab.research.google.com/github/Beatrix-0/Python-For-AI/blob/main/Numpy_fundamentals(session_13).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

# Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

# Creating Numpy Arrays

In [ ]:
import numpy as np

# np.array( create a array )
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
# 2D array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3D array (Tensor)
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# dtype(can change the data type )
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
# np.arange (create a array within a range (l,r,gap) )
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
# with reshape (reshape(m*n) a existing list )
np.arange(25).reshape(5,5)
# np.arange(16).reshape(2,2,2,2)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# np.ones( make a m*n matrix all value are 1 )
np.ones((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# and np.zeros ( make a m*n matrix all value are 0 )
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# and np.random ( make a m*n matrix all value are rand numvber )
np.random.random((3,4))

array([[0.85721156, 0.31248316, 0.08807828, 0.35230774],
       [0.96813914, 0.44681708, 0.56396358, 0.53020065],
       [0.03277116, 0.28543753, 0.09521082, 0.87967034]])

In [ ]:
# np.linspace = creates evenly spaced numbers in a range with a specified quantity
# np.linspace(start, stop, quantity, dtype=type)
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [ ]:
# np.identity = creates an identity matrix (square matrix with 1 on diagonal and 0 elsewhere)
# np.identity(n, dtype=type)
np.identity(3 , dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

# Array Attributes

In [ ]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# ndim = returns the number of dimensions (1D,2D,3D..) of an array
a3.ndim

3

In [ ]:
# shape = returns the size of each dimension of the array (rows, columns, etc.)
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# size = returns total number of elements in the array
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
# itemsize = returns the size (in bytes(occupaid by memory)) of each element in the array
a3.itemsize

8

In [ ]:
# dtype = datatype of the elements
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


# Changing Datatype

In [ ]:
# astype = converts array elements to a specified data type
# array.astype(dtype)
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
# scalar operations = applies an operation between an array and a single value (element-wise)

# arithmetic all operation can be done (+, -, *, / ...)
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
# relational operations = compares each element of the array with a value and returns a boolean array
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# vector operations = element-wise operations between two arrays of same shape
# arithmetic
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

# Array Functions

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[43., 28., 71.],
       [27., 93., 36.],
       [31., 18.,  7.]])

In [ ]:
# tmp = max/min/sum/prod
# returns the (tmp) of array elements  along axis
# 0 -> col and 1 -> row
# np.prod(array, axis=0/1)
np.prod(a1,axis=0)

array([35991., 46872., 17892.])

In [ ]:
# tmp = mean/median/std/var
# returns the (tmp) of array elements  along axis
# np.prod(array, axis=0/1)
np.var(a1,axis=1)

array([317.55555556, 854.        ,  96.22222222])

In [ ]:
# trigonomoetric functions
np.sin(a1)

array([[-0.83177474,  0.27090579,  0.95105465],
       [ 0.95637593, -0.94828214, -0.99177885],
       [-0.40403765, -0.75098725,  0.6569866 ]])

In [ ]:
# dot product = performs matrix multiplication between two compatible arrays
# condition = Columns of first matrix must equal rows of second matrix
# np.dot(matrix1, matrix2)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponents
np.log(a1)
np.exp(a1)

array([[4.72783947e+18, 1.44625706e+12, 6.83767123e+30],
       [5.32048241e+11, 2.45124554e+40, 4.31123155e+15],
       [2.90488497e+13, 6.56599691e+07, 1.09663316e+03]])

In [ ]:
# ceil = rounds each element of array UP to the nearest
# round = rounds each element of array NEAREST to the nearest integer
# flooor = rounds each element of array DOWN to the nearest integer

np.ceil(np.random.random((2,3))*100)

array([[48.,  4.,  6.],
       [ 3., 18., 82.]])

# Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1,0]

4

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1]

5

In [ ]:
a3[1,1,0]

6

In [ ]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# slicing = extracts a subset of elements from an array using start, stop, step
# array[start:stop:step]
a1[2:5:2]

array([2, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# array[row_start:row_end, col_start:col_end:step]
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1,::3]

array([4, 7])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
# nD slicing = selects elements from multidimensional arrays using slices per axis
# array[axis0_slice, axis1_index, axis2_slice]
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[0,1,:]

array([3, 4, 5])

# Iterating

In [ ]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
# iterating over all element
for i in np.nditer(a3): # convert nD array into 1D array, then iterate
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [ ]:
# reshape

In [ ]:
# transpose = swaps rows and columns of an array
# np.transpose(array) or array.T
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# ravel = convert a multi-dimensional array into a 1D array
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

In [ ]:
# horizontal stacking = joins arrays column-wise (side by side)
# np.hstack((array1, array2))
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# Vertical stacking = joins arrays row-wise (side by side)
# np.hstack((array1, array2))
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [ ]:
# horizontal splitting = splits an array into multiple sub-arrays column-wise
# np.hsplit(array, number_of_parts)
# print(a4)
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [ ]:
# vertical splitting = splits an array into multiple sub-arrays row-wise
# np.vsplit(array, number_of_parts)
# print(a5)
np.vsplit(a5,2)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


ValueError: array split does not result in an equal division